---
- name: Create group list (primary)
  set_fact:
    groups_to_add: "{{ [USERS_ANSIBLE_GROUP] }}"
  when: USERS_ANSIBLE_GROUP_ENABLED

- name: Create group list (primary)
  set_fact:
    groups_to_add: "{{ groups_to_add | default([]) | union([ item.group | default(item.username) ]) }}"
  loop: '{{ USERS }}'

- name: Create group list
  set_fact:
    groups_to_add: "{{ groups_to_add | default([]) | union( item.groups | default([]) ) }}"
  loop: '{{ USERS }}'

- name: Ensure groups exist
  group:
    name: "{{ item }}"
    state: present
  loop: '{{ groups_to_add }}'
