---
- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      - "vars/distro/{{ ansible_os_family }}.yml"
      - "vars/distro/default.yml"

- name: Install dependencies
  package:
    name: sudo
    state: present

- name: Create groups
  include_tasks: groups.yml

- name: Add/Update an user
  include_tasks: user.yml
  loop: '{{ USERS }}'

- name: Remove undesired users
  user:
    name: "{{ item.username }}"
    state: absent
    remove: true
  loop: '{{ USERS_TO_REMOVE }}'
