---
- name: Create group list
  set_fact:
    groups_to_add: "{{ item.groups | default([]) }}"

- name: Append sudoer group to group list
  set_fact:
    groups_to_add: "{{ groups_to_add + [ sudoer_group ] }}"
  when: item.sudoer | default(false)

- name: Create user with primary group and reset groups
  user:
    name: "{{ item.username }}"
    comment: "{{ item.name | default('') }}"
    group: "{{ item.group | default( item.username ) }}"
    groups: "{{ groups_to_add }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
