---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Update apt cache.
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

    - name: Add an user to remove.
      user:
        name: alice
        shell: /bin/bash
        append: true
